### PR TITLE
Update the plugin name in the logseq marketplace

### PR DESCRIPTION
**Pull request by jacksonh**

### CODE REVIEW

**Comment by sywhb** [comment]
I guess we need to update the `manifest.json` in logseql/marketPlace too:

Refer to this: https://github.com/logseq/marketplace/pull/206/files

**Comment by jacksonh** [comment]
Oh interesting, surprised both are needed. I guess we should. Maybe we need to wait until the next update though?

**Comment by sywhb** [comment]
Yeah, we can wait

**Comment by sywhb** [comment]
I will merge this one first and then submit a PR to the marketplace

**Pull request merged**
